//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> InterestedInCSharp { get; set; }
        public Nullable<bool> InterestedInJava { get; set; }
        public Nullable<bool> InterestedInPython { get; set; }
    }
}
